/**
 * Metis.AI Starter Workflow Pack System
 *
 * 4 Packs × 3 workflows each = 12 Production-Ready Templates
 * Each template includes: nodes, connectors, policies, parameters, failure paths
 *
 * Architecture:
 *   Pack → Workflow Template → Parameterized Nodes → Connector Contracts → Policy Checkpoints
 */

// ── Core Types ──

export type ConnectorTier = 'tier1-must' | 'tier2-reporting' | 'tier3-knowledge';
export type ConnectorStatus = 'available' | 'placeholder' | 'mcp-importable';
export type RiskLevel = 'low' | 'medium' | 'high' | 'critical';

export interface ConnectorContract {
  key: string;
  name: string;
  type: 'REST_API' | 'WEBHOOK' | 'MCP_SERVER' | 'DATABASE' | 'EMAIL' | 'CLI';
  tier: ConnectorTier;
  status: ConnectorStatus;
  actions: string[];
  requiredSecrets: string[];
  description: string;
}

export interface PolicyCheckpoint {
  id: string;
  name: string;
  when: string;
  riskLevel: RiskLevel;
  action: 'block' | 'warn' | 'log';
  description: string;
}

export interface WorkflowParameter {
  key: string;
  label: string;
  type: 'string' | 'number' | 'select' | 'boolean' | 'date-range';
  required: boolean;
  defaultValue?: string;
  options?: string[];
  description: string;
}

export interface TemplateNode {
  id: string;
  type: string;
  name: string;
  icon: string;
  color: string;
  order: number;
  connectorKey?: string;
  actionType: 'read' | 'write' | 'execute' | 'external-send' | 'deploy' | 'delete';
  policyCheckpoint?: string;
  failureAction: 'stop' | 'skip' | 'retry' | 'fallback';
  retryCount?: number;
  humanApproval?: boolean;
  description: string;
  outputKeys: string[];
  settings: Record<string, any>;
}

export interface WorkflowTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  packId: string;
  targetUser: string;
  businessOutcome: string;
  triggerType: string;
  parameters: WorkflowParameter[];
  nodes: TemplateNode[];
  connectors: string[]; // connector keys required
  policies: PolicyCheckpoint[];
  monitoringRequirements: string[];
  outputs: string[];
  estimatedDuration: string;
  tags: string[];
}

export interface StarterPack {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  category: string;
  workflowIds: string[];
  requiredConnectors: string[];
  version: string;
}

// ── Connector Registry ──

export const CONNECTOR_REGISTRY: ConnectorContract[] = [
  // Tier 1: Must-have IT Ops
  {
    key: 'jira',
    name: 'Jira / ITSM',
    type: 'REST_API',
    tier: 'tier1-must',
    status: 'placeholder',
    actions: [
      'create_ticket',
      'update_ticket',
      'get_ticket',
      'search_tickets',
      'add_comment',
      'transition',
    ],
    requiredSecrets: ['JIRA_URL', 'JIRA_API_TOKEN'],
    description: 'IT 서비스 관리 및 이슈 트래킹',
  },
  {
    key: 'github',
    name: 'GitHub',
    type: 'REST_API',
    tier: 'tier1-must',
    status: 'placeholder',
    actions: [
      'get_pr',
      'list_commits',
      'get_checks',
      'create_comment',
      'get_deployments',
      'list_releases',
    ],
    requiredSecrets: ['GITHUB_TOKEN'],
    description: '소스코드 및 배포 관리',
  },
  {
    key: 'slack',
    name: 'Slack',
    type: 'REST_API',
    tier: 'tier1-must',
    status: 'placeholder',
    actions: ['send_message', 'create_channel', 'upload_file', 'add_reaction'],
    requiredSecrets: ['SLACK_BOT_TOKEN'],
    description: '팀 커뮤니케이션',
  },
  {
    key: 'prometheus',
    name: 'Prometheus / Grafana',
    type: 'REST_API',
    tier: 'tier1-must',
    status: 'placeholder',
    actions: ['query_metrics', 'query_range', 'get_alerts', 'get_dashboard'],
    requiredSecrets: ['PROMETHEUS_URL', 'GRAFANA_API_KEY'],
    description: '메트릭 모니터링',
  },
  {
    key: 'kubernetes',
    name: 'Kubernetes',
    type: 'CLI',
    tier: 'tier1-must',
    status: 'placeholder',
    actions: ['get_pods', 'get_deployments', 'rollback', 'scale', 'get_events', 'get_logs'],
    requiredSecrets: ['KUBECONFIG'],
    description: '컨테이너 오케스트레이션',
  },
  {
    key: 'pagerduty',
    name: 'PagerDuty',
    type: 'REST_API',
    tier: 'tier1-must',
    status: 'placeholder',
    actions: ['create_incident', 'resolve_incident', 'get_oncall', 'trigger_alert'],
    requiredSecrets: ['PAGERDUTY_API_KEY'],
    description: '인시던트 관리 및 온콜',
  },
  {
    key: 'jenkins',
    name: 'Jenkins / ArgoCD',
    type: 'REST_API',
    tier: 'tier1-must',
    status: 'placeholder',
    actions: ['trigger_build', 'get_build_status', 'get_pipeline', 'get_artifacts'],
    requiredSecrets: ['JENKINS_URL', 'JENKINS_TOKEN'],
    description: 'CI/CD 파이프라인',
  },
  {
    key: 'elk',
    name: 'ELK / Splunk',
    type: 'REST_API',
    tier: 'tier1-must',
    status: 'placeholder',
    actions: ['search_logs', 'get_log_pattern', 'get_error_count', 'create_alert'],
    requiredSecrets: ['ELASTICSEARCH_URL'],
    description: '로그 검색 및 분석',
  },
  // Tier 2: Manager / Reporting
  {
    key: 'email-smtp',
    name: 'Email (SMTP)',
    type: 'EMAIL',
    tier: 'tier2-reporting',
    status: 'available',
    actions: ['send_email', 'send_html_email'],
    requiredSecrets: ['SMTP_HOST', 'SMTP_USER', 'SMTP_PASS'],
    description: '이메일 발송 (SMTP)',
  },
  {
    key: 'confluence',
    name: 'Confluence / Notion',
    type: 'REST_API',
    tier: 'tier2-reporting',
    status: 'placeholder',
    actions: ['create_page', 'update_page', 'search', 'get_page'],
    requiredSecrets: ['CONFLUENCE_URL', 'CONFLUENCE_TOKEN'],
    description: '문서 관리',
  },
  {
    key: 'teams',
    name: 'Microsoft Teams',
    type: 'WEBHOOK',
    tier: 'tier2-reporting',
    status: 'placeholder',
    actions: ['send_message', 'send_card'],
    requiredSecrets: ['TEAMS_WEBHOOK_URL'],
    description: 'Teams 알림',
  },
  // Tier 3: Data / Knowledge
  {
    key: 'postgresql',
    name: 'PostgreSQL',
    type: 'DATABASE',
    tier: 'tier3-knowledge',
    status: 'available',
    actions: ['query', 'insert', 'update'],
    requiredSecrets: ['DATABASE_URL'],
    description: 'CMDB / 데이터 저장소',
  },
  {
    key: 's3',
    name: 'S3 / Cloud Storage',
    type: 'REST_API',
    tier: 'tier3-knowledge',
    status: 'placeholder',
    actions: ['upload', 'download', 'list'],
    requiredSecrets: ['AWS_ACCESS_KEY', 'AWS_SECRET_KEY', 'S3_BUCKET'],
    description: 'Evidence / 아티팩트 저장',
  },
  {
    key: 'metis-knowledge',
    name: 'Metis Knowledge Registry',
    type: 'REST_API',
    tier: 'tier3-knowledge',
    status: 'available',
    actions: ['search', 'create_entry', 'update_entry', 'link_artifact'],
    requiredSecrets: [],
    description: 'Metis 내부 지식 베이스',
  },
  {
    key: 'metis-audit',
    name: 'Metis Audit Log',
    type: 'REST_API',
    tier: 'tier3-knowledge',
    status: 'available',
    actions: ['write_log', 'query_logs'],
    requiredSecrets: [],
    description: 'Metis 감사 로그',
  },
  {
    key: 'metis-evidence',
    name: 'Metis Evidence Pack',
    type: 'REST_API',
    tier: 'tier3-knowledge',
    status: 'available',
    actions: ['create_pack', 'add_artifact', 'seal_pack'],
    requiredSecrets: [],
    description: 'Evidence Pack 생성',
  },
];

// ── 12 Starter Workflow Templates ──

export const WORKFLOW_TEMPLATES: WorkflowTemplate[] = [
  // ═══════════════════════════════════════════════
  // Pack 1: Incident Ops Pack
  // ═══════════════════════════════════════════════

  // WF-1: Incident Intake Triage
  {
    id: 'wf-incident-triage',
    name: '장애 접수 Triage 자동화',
    description:
      '새 인시던트 티켓 생성 시 자동으로 컨텍스트 수집, 심각도 분류, 관련 런북 연결, 운영자 알림까지 수행',
    category: '자동화',
    packId: 'pack-incident-ops',
    targetUser: 'IT 운영자',
    businessOutcome: '초기 대응 시간 단축 및 Triage 표준화 (MTTR 40% 감소 목표)',
    triggerType: 'ITSM 티켓 생성',
    parameters: [
      {
        key: 'incident_id',
        label: '인시던트 ID',
        type: 'string',
        required: true,
        description: 'ITSM 인시던트 티켓 ID',
      },
      {
        key: 'service_name',
        label: '서비스명',
        type: 'string',
        required: true,
        description: '장애 발생 서비스',
      },
      {
        key: 'priority',
        label: '우선순위',
        type: 'select',
        required: true,
        options: ['P1-Critical', 'P2-High', 'P3-Medium', 'P4-Low'],
        description: '인시던트 우선순위',
      },
      {
        key: 'environment',
        label: '환경',
        type: 'select',
        required: true,
        options: ['production', 'staging', 'development'],
        defaultValue: 'production',
        description: '영향 환경',
      },
      {
        key: 'reporter',
        label: '보고자',
        type: 'string',
        required: false,
        description: '최초 보고자',
      },
    ],
    nodes: [
      {
        id: 'n1',
        type: 'webhook',
        name: 'ITSM Webhook 수신',
        icon: '🔗',
        color: '#8B4513',
        order: 1,
        connectorKey: 'jira',
        actionType: 'read',
        failureAction: 'stop',
        description: 'ITSM에서 새 인시던트 티켓 생성 이벤트 수신',
        outputKeys: ['incident_id', 'service_name', 'priority', 'description', 'reporter'],
        settings: { method: 'POST', path: '/webhook/incident' },
      },
      {
        id: 'n2',
        type: 'api-call',
        name: '인시던트 상세 로드',
        icon: '🌐',
        color: '#FF6348',
        order: 2,
        connectorKey: 'jira',
        actionType: 'read',
        failureAction: 'stop',
        description: 'ITSM에서 인시던트 전체 상세 정보 조회',
        outputKeys: ['full_incident', 'attachments', 'related_tickets'],
        settings: { method: 'GET', url: '/api/incident/{incident_id}' },
      },
      {
        id: 'n3',
        type: 'api-call',
        name: '최근 배포/장애 이력 조회',
        icon: '🌐',
        color: '#FF6348',
        order: 3,
        connectorKey: 'github',
        actionType: 'read',
        failureAction: 'skip',
        description: '최근 24시간 배포 이력 및 유사 장애 검색',
        outputKeys: ['recent_deployments', 'related_incidents'],
        settings: { method: 'GET', url: '/api/deployments/recent' },
      },
      {
        id: 'n4',
        type: 'log-monitor',
        name: '로그/메트릭 수집',
        icon: '📊',
        color: '#20B2AA',
        order: 4,
        connectorKey: 'elk',
        actionType: 'read',
        failureAction: 'skip',
        description: '대상 서비스의 에러 로그 및 메트릭 이상 징후 수집',
        outputKeys: ['error_logs', 'metric_anomalies', 'error_rate'],
        settings: { logLevel: 'error', destination: 'analysis' },
      },
      {
        id: 'n5',
        type: 'api-call',
        name: 'Knowledge Registry 조회',
        icon: '🌐',
        color: '#FF6348',
        order: 5,
        connectorKey: 'metis-knowledge',
        actionType: 'read',
        failureAction: 'skip',
        description: '유사 장애 패턴 및 관련 런북 검색',
        outputKeys: ['matched_patterns', 'runbooks', 'known_errors'],
        settings: { method: 'POST', url: '/knowledge/search' },
      },
      {
        id: 'n6',
        type: 'condition',
        name: '정책 점검 (외부 알림 전)',
        icon: '⚡',
        color: '#F77F00',
        order: 6,
        actionType: 'read',
        policyCheckpoint: 'pol-1',
        failureAction: 'stop',
        description: '외부 알림/자동 조치 전 거버넌스 정책 확인',
        outputKeys: ['policy_result', 'blocked_actions'],
        settings: { conditionExpression: 'policy.result === "PASS"' },
      },
      {
        id: 'n7',
        type: 'ai-processing',
        name: '심각도 분류 & Triage',
        icon: '🤖',
        color: '#6C5CE7',
        order: 7,
        actionType: 'execute',
        failureAction: 'fallback',
        description: 'AI 기반 심각도 재분류, 장애 카테고리 결정, 초기 대응 제안',
        outputKeys: [
          'severity',
          'category',
          'triage_summary',
          'recommended_actions',
          'probable_causes',
        ],
        settings: {
          agentName: 'incident-triage-agent',
          model: 'claude-sonnet-4.6',
          promptTemplate: 'Triage incident based on logs, metrics, and knowledge',
          finopsEnabled: true,
        },
      },
      {
        id: 'n8',
        type: 'condition',
        name: 'Critical 확인 → 수동 승인',
        icon: '⚡',
        color: '#F77F00',
        order: 8,
        actionType: 'read',
        humanApproval: true,
        failureAction: 'stop',
        description: 'P1 Critical이면 운영자 확인 후 자동 조치 진행',
        outputKeys: ['approval_result'],
        settings: { conditionExpression: 'severity === "P1-Critical"' },
      },
      {
        id: 'n9',
        type: 'slack-message',
        name: '운영 채널 알림',
        icon: '💬',
        color: '#00B894',
        order: 9,
        connectorKey: 'slack',
        actionType: 'external-send',
        failureAction: 'retry',
        retryCount: 2,
        description: '구조화된 Triage 요약을 운영 Slack 채널에 전송',
        outputKeys: ['notification_sent'],
        settings: { channel: '#ops-incidents', messageTemplate: 'Triage Summary' },
      },
      {
        id: 'n10',
        type: 'data-storage',
        name: '감사 로그 기록',
        icon: '💾',
        color: '#00A8CC',
        order: 10,
        connectorKey: 'metis-audit',
        actionType: 'write',
        failureAction: 'retry',
        retryCount: 3,
        description: '전체 Triage 과정 감사 로그 기록',
        outputKeys: ['audit_id'],
        settings: { storageType: 'audit_log', operation: 'INSERT' },
      },
      {
        id: 'n11',
        type: 'data-storage',
        name: 'Evidence Pack 생성',
        icon: '💾',
        color: '#00A8CC',
        order: 11,
        connectorKey: 'metis-evidence',
        actionType: 'write',
        failureAction: 'skip',
        description: '로그, 메트릭, Triage 결과를 Evidence Pack으로 묶기',
        outputKeys: ['evidence_pack_id'],
        settings: { storageType: 'evidence', operation: 'CREATE_PACK' },
      },
      {
        id: 'n12',
        type: 'notification',
        name: '모니터링 대시보드 업데이트',
        icon: '🔔',
        color: '#228B22',
        order: 12,
        actionType: 'write',
        failureAction: 'skip',
        description: '실행 모니터링 뷰에 진행 상황 반영',
        outputKeys: ['dashboard_updated'],
        settings: { channel: 'dashboard' },
      },
    ],
    connectors: [
      'jira',
      'github',
      'elk',
      'metis-knowledge',
      'slack',
      'metis-audit',
      'metis-evidence',
    ],
    policies: [
      {
        id: 'pol-1',
        name: '외부 알림 전 정책 점검',
        when: '외부 시스템 알림/자동 조치 전',
        riskLevel: 'high',
        action: 'block',
        description: 'external-send/deploy 액션 실행 전 거버넌스 정책 확인',
      },
    ],
    monitoringRequirements: [
      '노드별 실행 상태',
      '전체 진행률',
      'AI Triage 결과 요약',
      '정책 위반 여부',
    ],
    outputs: ['Triage 요약서', '추정 근본 원인', '권장 조치', '연관 런북', '감사/Evidence 참조'],
    estimatedDuration: '30-90초',
    tags: ['incident', 'triage', 'automation', 'MTTR'],
  },

  // WF-2: Alert Deduplication
  {
    id: 'wf-alert-dedup',
    name: '알림 중복 제거 & 그룹핑',
    description:
      '모니터링 알림이 발생하면 중복 여부를 판단하고, 기존 인시던트에 연결하거나 새 인시던트를 생성',
    category: '자동화',
    packId: 'pack-incident-ops',
    targetUser: 'IT 운영자',
    businessOutcome: '알림 피로도 감소 (중복 알림 70% 이상 필터링)',
    triggerType: '모니터링 알림 발생',
    parameters: [
      {
        key: 'alert_id',
        label: '알림 ID',
        type: 'string',
        required: true,
        description: '모니터링 알림 ID',
      },
      {
        key: 'service_name',
        label: '서비스명',
        type: 'string',
        required: true,
        description: '알림 발생 서비스',
      },
      {
        key: 'alert_type',
        label: '알림 유형',
        type: 'select',
        required: true,
        options: ['error_rate', 'latency', 'saturation', 'availability', 'security'],
        description: '알림 카테고리',
      },
    ],
    nodes: [
      {
        id: 'n1',
        type: 'webhook',
        name: '알림 수신',
        icon: '🔗',
        color: '#8B4513',
        order: 1,
        connectorKey: 'pagerduty',
        actionType: 'read',
        failureAction: 'stop',
        description: '모니터링 시스템에서 알림 수신',
        outputKeys: ['alert_payload'],
        settings: {},
      },
      {
        id: 'n2',
        type: 'api-call',
        name: '활성 인시던트 조회',
        icon: '🌐',
        color: '#FF6348',
        order: 2,
        connectorKey: 'jira',
        actionType: 'read',
        failureAction: 'skip',
        description: '동일 서비스의 활성 인시던트 조회',
        outputKeys: ['active_incidents'],
        settings: {},
      },
      {
        id: 'n3',
        type: 'ai-processing',
        name: '중복/유사 분석',
        icon: '🤖',
        color: '#6C5CE7',
        order: 3,
        actionType: 'execute',
        failureAction: 'fallback',
        description: 'AI로 알림 중복 여부 및 기존 인시던트 연관성 판단',
        outputKeys: ['is_duplicate', 'related_incident_id', 'confidence'],
        settings: {
          agentName: 'alert-dedup-agent',
          model: 'claude-haiku-4.5',
          finopsEnabled: true,
        },
      },
      {
        id: 'n4',
        type: 'condition',
        name: '중복 여부 분기',
        icon: '⚡',
        color: '#F77F00',
        order: 4,
        actionType: 'read',
        failureAction: 'stop',
        description: '중복이면 기존 인시던트에 연결, 아니면 새로 생성',
        outputKeys: ['action_type'],
        settings: {},
      },
      {
        id: 'n5',
        type: 'api-call',
        name: '인시던트 업데이트/생성',
        icon: '🌐',
        color: '#FF6348',
        order: 5,
        connectorKey: 'jira',
        actionType: 'write',
        failureAction: 'retry',
        retryCount: 2,
        description: '중복이면 코멘트 추가, 신규면 인시던트 생성',
        outputKeys: ['incident_id'],
        settings: {},
      },
      {
        id: 'n6',
        type: 'data-storage',
        name: '감사 로그',
        icon: '💾',
        color: '#00A8CC',
        order: 6,
        connectorKey: 'metis-audit',
        actionType: 'write',
        failureAction: 'skip',
        description: '중복 판단 결과 및 조치 기록',
        outputKeys: ['audit_id'],
        settings: {},
      },
    ],
    connectors: ['pagerduty', 'jira', 'metis-audit'],
    policies: [
      {
        id: 'pol-1',
        name: '인시던트 생성 정책',
        when: '신규 인시던트 생성 전',
        riskLevel: 'medium',
        action: 'warn',
        description: '중복 판단 신뢰도가 낮을 때 경고',
      },
    ],
    monitoringRequirements: ['중복 판단 결과', '필터링 비율'],
    outputs: ['중복 판단 결과', '연결된/생성된 인시던트 ID', '감사 기록'],
    estimatedDuration: '5-15초',
    tags: ['alert', 'deduplication', 'noise-reduction'],
  },

  // WF-3: RCA Draft Generator
  {
    id: 'wf-rca-draft',
    name: 'RCA 초안 자동 생성',
    description:
      '해결된 인시던트의 타임라인, 로그, 메트릭을 수집하여 RCA(Root Cause Analysis) 초안을 자동 생성',
    category: '자동화',
    packId: 'pack-incident-ops',
    targetUser: 'IT 운영자',
    businessOutcome: 'RCA 작성 시간 70% 단축, 품질 표준화',
    triggerType: '인시던트 해결 완료',
    parameters: [
      {
        key: 'incident_id',
        label: '인시던트 ID',
        type: 'string',
        required: true,
        description: '해결된 인시던트 ID',
      },
      {
        key: 'resolution_summary',
        label: '해결 요약',
        type: 'string',
        required: true,
        description: '해결 조치 요약',
      },
    ],
    nodes: [
      {
        id: 'n1',
        type: 'webhook',
        name: '인시던트 해결 이벤트',
        icon: '🔗',
        color: '#8B4513',
        order: 1,
        connectorKey: 'jira',
        actionType: 'read',
        failureAction: 'stop',
        description: '인시던트 상태가 Resolved로 변경 시 트리거',
        outputKeys: ['incident_data'],
        settings: {},
      },
      {
        id: 'n2',
        type: 'api-call',
        name: '전체 타임라인 수집',
        icon: '🌐',
        color: '#FF6348',
        order: 2,
        connectorKey: 'jira',
        actionType: 'read',
        failureAction: 'stop',
        description: '인시던트 전체 이력, 코멘트, 관련 변경사항 수집',
        outputKeys: ['timeline', 'comments', 'changes'],
        settings: {},
      },
      {
        id: 'n3',
        type: 'log-monitor',
        name: '장애 구간 로그 수집',
        icon: '📊',
        color: '#20B2AA',
        order: 3,
        connectorKey: 'elk',
        actionType: 'read',
        failureAction: 'skip',
        description: '장애 발생~해결 구간 로그 및 메트릭 수집',
        outputKeys: ['logs', 'metrics'],
        settings: {},
      },
      {
        id: 'n4',
        type: 'ai-processing',
        name: 'RCA 초안 생성',
        icon: '🤖',
        color: '#6C5CE7',
        order: 4,
        actionType: 'execute',
        failureAction: 'fallback',
        description: 'AI로 5-Why, 타임라인, 근본원인, 재발방지 포함 RCA 초안 작성',
        outputKeys: ['rca_draft', 'root_causes', 'prevention_actions'],
        settings: { agentName: 'rca-agent', model: 'claude-sonnet-4.6', finopsEnabled: true },
      },
      {
        id: 'n5',
        type: 'wait-approval',
        name: '검토자 승인',
        icon: '⏳',
        color: '#D62828',
        order: 5,
        actionType: 'read',
        humanApproval: true,
        failureAction: 'stop',
        description: '담당자가 RCA 초안 검토 후 승인',
        outputKeys: ['approval'],
        settings: { waitType: 'approval', timeoutMinutes: 1440 },
      },
      {
        id: 'n6',
        type: 'api-call',
        name: 'Confluence 게시',
        icon: '🌐',
        color: '#FF6348',
        order: 6,
        connectorKey: 'confluence',
        actionType: 'write',
        failureAction: 'retry',
        retryCount: 2,
        description: '승인된 RCA를 문서 시스템에 게시',
        outputKeys: ['page_url'],
        settings: {},
      },
      {
        id: 'n7',
        type: 'data-storage',
        name: 'Evidence Pack 연결',
        icon: '💾',
        color: '#00A8CC',
        order: 7,
        connectorKey: 'metis-evidence',
        actionType: 'write',
        failureAction: 'skip',
        description: 'RCA 문서와 관련 로그/메트릭을 Evidence Pack으로 묶기',
        outputKeys: ['evidence_id'],
        settings: {},
      },
    ],
    connectors: ['jira', 'elk', 'confluence', 'metis-evidence'],
    policies: [
      {
        id: 'pol-1',
        name: 'RCA 게시 전 검토',
        when: 'RCA 문서 외부 게시 전',
        riskLevel: 'medium',
        action: 'block',
        description: '검토자 승인 없이 RCA 게시 차단',
      },
    ],
    monitoringRequirements: ['RCA 생성 완료 여부', '검토 대기 시간'],
    outputs: ['RCA 초안', '근본 원인 목록', '재발 방지 조치', 'Evidence Pack'],
    estimatedDuration: '60-120초 (AI 생성) + 검토 시간',
    tags: ['incident', 'rca', 'post-mortem'],
  },

  // ═══════════════════════════════════════════════
  // Pack 2: Release Ops Pack
  // ═══════════════════════════════════════════════

  // WF-4: Pre-Deployment Readiness Gate
  {
    id: 'wf-pre-deploy-gate',
    name: '배포 전 점검 게이트',
    description:
      '배포 승인 요청 시 PR 상태, 테스트, 보안 스캔, 의존성, 활성 인시던트를 종합 점검하여 배포 가/부 판정',
    category: '배포',
    packId: 'pack-release-ops',
    targetUser: 'IT 운영자 / 릴리스 관리자',
    businessOutcome: '실패 배포 방지 (배포 실패율 60% 감소)',
    triggerType: '배포 승인 요청',
    parameters: [
      {
        key: 'change_id',
        label: '변경 ID',
        type: 'string',
        required: true,
        description: '변경 관리 ID',
      },
      {
        key: 'release_id',
        label: '릴리스 ID',
        type: 'string',
        required: true,
        description: '릴리스 버전',
      },
      {
        key: 'repo',
        label: '저장소',
        type: 'string',
        required: true,
        description: 'GitHub 저장소',
      },
      {
        key: 'target_env',
        label: '대상 환경',
        type: 'select',
        required: true,
        options: ['production', 'staging', 'canary'],
        description: '배포 대상 환경',
      },
      {
        key: 'service_name',
        label: '서비스명',
        type: 'string',
        required: true,
        description: '배포 대상 서비스',
      },
    ],
    nodes: [
      {
        id: 'n1',
        type: 'webhook',
        name: '배포 요청 수신',
        icon: '🔗',
        color: '#8B4513',
        order: 1,
        actionType: 'read',
        failureAction: 'stop',
        description: '배포 승인 요청 이벤트 수신',
        outputKeys: ['deploy_request'],
        settings: {},
      },
      {
        id: 'n2',
        type: 'api-call',
        name: 'PR/MR 상태 확인',
        icon: '🌐',
        color: '#FF6348',
        order: 2,
        connectorKey: 'github',
        actionType: 'read',
        failureAction: 'stop',
        description: 'PR 승인, 테스트, 보안 스캔 결과 확인',
        outputKeys: ['pr_status', 'test_results', 'security_scan'],
        settings: {},
      },
      {
        id: 'n3',
        type: 'api-call',
        name: '활성 인시던트 확인',
        icon: '🌐',
        color: '#FF6348',
        order: 3,
        connectorKey: 'jira',
        actionType: 'read',
        failureAction: 'skip',
        description: '해당 서비스에 활성 P1/P2 인시던트 존재 여부',
        outputKeys: ['active_incidents'],
        settings: {},
      },
      {
        id: 'n4',
        type: 'condition',
        name: '정책 점검 (배포 위험도)',
        icon: '⚡',
        color: '#F77F00',
        order: 4,
        actionType: 'read',
        policyCheckpoint: 'pol-1',
        failureAction: 'stop',
        description: '보호 환경 배포 규칙, 배포 금지 시간대 확인',
        outputKeys: ['policy_result'],
        settings: {},
      },
      {
        id: 'n5',
        type: 'ai-processing',
        name: '배포 준비도 점수 산출',
        icon: '🤖',
        color: '#6C5CE7',
        order: 5,
        actionType: 'execute',
        failureAction: 'fallback',
        description: 'AI로 PR, 테스트, 보안, 의존성, 인시던트 종합 분석하여 점수 산출',
        outputKeys: ['readiness_score', 'blocking_reasons', 'risk_summary'],
        settings: {
          agentName: 'deploy-gate-agent',
          model: 'claude-sonnet-4.6',
          finopsEnabled: true,
        },
      },
      {
        id: 'n6',
        type: 'condition',
        name: '점수 임계값 판단',
        icon: '⚡',
        color: '#F77F00',
        order: 6,
        actionType: 'read',
        failureAction: 'stop',
        description: '점수가 임계값 미달이면 차단 및 사유 설명',
        outputKeys: ['pass_fail'],
        settings: {},
      },
      {
        id: 'n7',
        type: 'wait-approval',
        name: '관리자 승인 (Production)',
        icon: '⏳',
        color: '#D62828',
        order: 7,
        actionType: 'read',
        humanApproval: true,
        failureAction: 'stop',
        description: 'Production 배포 시 관리자 명시적 승인 필요',
        outputKeys: ['manager_approval'],
        settings: {},
      },
      {
        id: 'n8',
        type: 'data-storage',
        name: '감사 로그',
        icon: '💾',
        color: '#00A8CC',
        order: 8,
        connectorKey: 'metis-audit',
        actionType: 'write',
        failureAction: 'retry',
        retryCount: 3,
        description: '배포 판정 결과 및 근거 감사 기록',
        outputKeys: ['audit_id'],
        settings: {},
      },
      {
        id: 'n9',
        type: 'slack-message',
        name: '결과 알림',
        icon: '💬',
        color: '#00B894',
        order: 9,
        connectorKey: 'slack',
        actionType: 'external-send',
        failureAction: 'skip',
        description: '배포 승인/차단 결과를 릴리스 채널에 알림',
        outputKeys: ['notified'],
        settings: {},
      },
    ],
    connectors: ['github', 'jira', 'slack', 'metis-audit'],
    policies: [
      {
        id: 'pol-1',
        name: '배포 위험도 정책',
        when: '배포 실행 전',
        riskLevel: 'critical',
        action: 'block',
        description: '보호 환경/배포 금지 시간대 규칙 적용',
      },
    ],
    monitoringRequirements: ['배포 준비도 점수', '차단 사유', '승인 대기 시간'],
    outputs: ['Pass/Fail 판정', '차단 사유', '승인 이력', '감사 기록'],
    estimatedDuration: '15-45초 + 승인 시간',
    tags: ['deployment', 'gate', 'safety'],
  },

  // WF-5: Post-Deployment Verification
  {
    id: 'wf-post-deploy-verify',
    name: '배포 후 검증 & 롤백 추천',
    description: '배포 완료 후 KPI 비교, 에러율 감시, 이상 감지 시 롤백 추천',
    category: '배포',
    packId: 'pack-release-ops',
    targetUser: 'IT 운영자',
    businessOutcome: '불량 배포 조기 감지 (MTTD 80% 단축)',
    triggerType: '배포 완료',
    parameters: [
      {
        key: 'release_id',
        label: '릴리스 ID',
        type: 'string',
        required: true,
        description: '배포 릴리스 ID',
      },
      {
        key: 'service_name',
        label: '서비스명',
        type: 'string',
        required: true,
        description: '배포 서비스',
      },
      {
        key: 'environment',
        label: '환경',
        type: 'select',
        required: true,
        options: ['production', 'staging', 'canary'],
        description: '배포 환경',
      },
    ],
    nodes: [
      {
        id: 'n1',
        type: 'webhook',
        name: '배포 완료 이벤트',
        icon: '🔗',
        color: '#8B4513',
        order: 1,
        actionType: 'read',
        failureAction: 'stop',
        description: 'CI/CD에서 배포 완료 이벤트 수신',
        outputKeys: ['deploy_info'],
        settings: {},
      },
      {
        id: 'n2',
        type: 'api-call',
        name: '배포 전/후 KPI 수집',
        icon: '🌐',
        color: '#FF6348',
        order: 2,
        connectorKey: 'prometheus',
        actionType: 'read',
        failureAction: 'stop',
        description: '에러율, 레이턴시, 포화도, 가용성 메트릭 비교',
        outputKeys: ['pre_metrics', 'post_metrics'],
        settings: {},
      },
      {
        id: 'n3',
        type: 'condition',
        name: 'Canary 임계값 체크',
        icon: '⚡',
        color: '#F77F00',
        order: 3,
        actionType: 'read',
        policyCheckpoint: 'pol-1',
        failureAction: 'stop',
        description: '에러율/레이턴시 증가가 임계값 초과 여부',
        outputKeys: ['health_verdict'],
        settings: {},
      },
      {
        id: 'n4',
        type: 'ai-processing',
        name: '배포 건강도 판정',
        icon: '🤖',
        color: '#6C5CE7',
        order: 4,
        actionType: 'execute',
        failureAction: 'fallback',
        description: 'Pass/Watch/Fail 상태 판정 및 롤백 추천',
        outputKeys: ['verdict', 'rollback_recommendation', 'metrics_summary'],
        settings: {
          agentName: 'deploy-verify-agent',
          model: 'claude-sonnet-4.6',
          finopsEnabled: true,
        },
      },
      {
        id: 'n5',
        type: 'condition',
        name: 'Fail → 롤백 알림',
        icon: '⚡',
        color: '#F77F00',
        order: 5,
        actionType: 'read',
        failureAction: 'stop',
        description: 'Fail이면 관리자에게 롤백 추천 발송',
        outputKeys: ['action'],
        settings: {},
      },
      {
        id: 'n6',
        type: 'slack-message',
        name: '검증 결과 알림',
        icon: '💬',
        color: '#00B894',
        order: 6,
        connectorKey: 'slack',
        actionType: 'external-send',
        failureAction: 'skip',
        description: '배포 검증 결과를 운영 채널에 알림',
        outputKeys: ['notified'],
        settings: {},
      },
      {
        id: 'n7',
        type: 'data-storage',
        name: '감사 로그 + Evidence',
        icon: '💾',
        color: '#00A8CC',
        order: 7,
        connectorKey: 'metis-audit',
        actionType: 'write',
        failureAction: 'retry',
        retryCount: 3,
        description: '배포 검증 결과 기록',
        outputKeys: ['audit_id'],
        settings: {},
      },
    ],
    connectors: ['prometheus', 'slack', 'metis-audit'],
    policies: [
      {
        id: 'pol-1',
        name: 'Canary 중단 임계값',
        when: '메트릭 비교 후',
        riskLevel: 'high',
        action: 'block',
        description: '에러율 5% 이상 증가 시 자동 경고',
      },
    ],
    monitoringRequirements: ['배포 건강도 점수', '메트릭 비교 차트', '롤백 권장 여부'],
    outputs: ['배포 건강도 판정', '롤백 추천', '메트릭 비교', '감사 기록'],
    estimatedDuration: '30-60초',
    tags: ['deployment', 'verification', 'rollback'],
  },

  // WF-6: DB Backup & Validation
  {
    id: 'wf-db-backup',
    name: 'DB 백업 & 검증',
    description: '정해진 시간에 DB 백업 실행, 무결성 검증, 실패 시 알림',
    category: '데이터',
    packId: 'pack-release-ops',
    targetUser: 'IT 운영자',
    businessOutcome: '데이터 손실 위험 제거',
    triggerType: '스케줄 (매일 02:00)',
    parameters: [
      {
        key: 'database_name',
        label: 'DB명',
        type: 'string',
        required: true,
        description: '백업 대상 DB',
      },
      {
        key: 'retention_days',
        label: '보관 기간(일)',
        type: 'number',
        required: true,
        defaultValue: '30',
        description: '백업 보관 기간',
      },
    ],
    nodes: [
      {
        id: 'n1',
        type: 'schedule',
        name: '일간 백업 스케줄',
        icon: '⏰',
        color: '#FF6B6B',
        order: 1,
        actionType: 'read',
        failureAction: 'stop',
        description: '매일 02:00 트리거',
        outputKeys: ['trigger_time'],
        settings: { scheduleType: '매일 반복', scheduleTime: '02:00' },
      },
      {
        id: 'n2',
        type: 'api-call',
        name: 'DB 백업 실행',
        icon: '🌐',
        color: '#FF6348',
        order: 2,
        connectorKey: 'postgresql',
        actionType: 'execute',
        failureAction: 'retry',
        retryCount: 2,
        description: 'pg_dump 또는 managed backup 실행',
        outputKeys: ['backup_id', 'backup_size'],
        settings: {},
      },
      {
        id: 'n3',
        type: 'api-call',
        name: '백업 무결성 검증',
        icon: '🌐',
        color: '#FF6348',
        order: 3,
        connectorKey: 'postgresql',
        actionType: 'read',
        failureAction: 'stop',
        description: '백업 파일 체크섬 및 복원 테스트',
        outputKeys: ['validation_result'],
        settings: {},
      },
      {
        id: 'n4',
        type: 'data-storage',
        name: '백업 메타데이터 저장',
        icon: '💾',
        color: '#00A8CC',
        order: 4,
        connectorKey: 's3',
        actionType: 'write',
        failureAction: 'retry',
        retryCount: 2,
        description: '백업 파일을 S3/Cloud Storage에 저장',
        outputKeys: ['storage_path'],
        settings: {},
      },
      {
        id: 'n5',
        type: 'email-send',
        name: '결과 리포트',
        icon: '📧',
        color: '#A29BFE',
        order: 5,
        connectorKey: 'email-smtp',
        actionType: 'external-send',
        failureAction: 'skip',
        description: '백업 결과를 관리자에게 이메일 발송',
        outputKeys: ['email_sent'],
        settings: {},
      },
      {
        id: 'n6',
        type: 'data-storage',
        name: '감사 로그',
        icon: '💾',
        color: '#00A8CC',
        order: 6,
        connectorKey: 'metis-audit',
        actionType: 'write',
        failureAction: 'skip',
        description: '백업 수행 감사 기록',
        outputKeys: ['audit_id'],
        settings: {},
      },
    ],
    connectors: ['postgresql', 's3', 'email-smtp', 'metis-audit'],
    policies: [],
    monitoringRequirements: ['백업 성공/실패', '백업 크기', '소요 시간'],
    outputs: ['백업 결과', '검증 결과', '저장 경로', '감사 기록'],
    estimatedDuration: '5-30분',
    tags: ['backup', 'database', 'validation'],
  },

  // ═══════════════════════════════════════════════
  // Pack 3: Governance Pack
  // ═══════════════════════════════════════════════

  // WF-7: Vulnerability Patch Coordination
  {
    id: 'wf-vuln-patch',
    name: '취약점 패치 조율',
    description: '보안 취약점 발견 시 영향 범위 분석, 패치 우선순위 결정, 패치 일정 조율',
    category: '자동화',
    packId: 'pack-governance',
    targetUser: 'IT 운영자',
    businessOutcome: '취약점 패치 주기 단축 (평균 5일 → 2일)',
    triggerType: '보안 스캔 결과 수신',
    parameters: [
      {
        key: 'vuln_id',
        label: '취약점 ID',
        type: 'string',
        required: true,
        description: 'CVE 또는 내부 취약점 ID',
      },
      {
        key: 'severity',
        label: '심각도',
        type: 'select',
        required: true,
        options: ['critical', 'high', 'medium', 'low'],
        description: 'CVSS 기반 심각도',
      },
    ],
    nodes: [
      {
        id: 'n1',
        type: 'webhook',
        name: '취약점 알림 수신',
        icon: '🔗',
        color: '#8B4513',
        order: 1,
        actionType: 'read',
        failureAction: 'stop',
        description: '보안 스캐너에서 취약점 알림 수신',
        outputKeys: ['vuln_data'],
        settings: {},
      },
      {
        id: 'n2',
        type: 'api-call',
        name: '영향 서비스 분석',
        icon: '🌐',
        color: '#FF6348',
        order: 2,
        connectorKey: 'github',
        actionType: 'read',
        failureAction: 'skip',
        description: '취약 라이브러리를 사용하는 서비스 목록 조회',
        outputKeys: ['affected_services'],
        settings: {},
      },
      {
        id: 'n3',
        type: 'ai-processing',
        name: '패치 우선순위 산출',
        icon: '🤖',
        color: '#6C5CE7',
        order: 3,
        actionType: 'execute',
        failureAction: 'fallback',
        description: 'CVSS, 영향 범위, 비즈니스 중요도 기반 패치 우선순위 결정',
        outputKeys: ['priority_list', 'patch_plan'],
        settings: {
          agentName: 'vuln-patch-agent',
          model: 'claude-sonnet-4.6',
          finopsEnabled: true,
        },
      },
      {
        id: 'n4',
        type: 'jira',
        name: '패치 티켓 생성',
        icon: '🎫',
        color: '#1E90FF',
        order: 4,
        connectorKey: 'jira',
        actionType: 'write',
        failureAction: 'retry',
        retryCount: 2,
        description: '서비스별 패치 티켓 자동 생성',
        outputKeys: ['ticket_ids'],
        settings: {},
      },
      {
        id: 'n5',
        type: 'slack-message',
        name: '보안팀 알림',
        icon: '💬',
        color: '#00B894',
        order: 5,
        connectorKey: 'slack',
        actionType: 'external-send',
        failureAction: 'skip',
        description: '패치 계획 요약을 보안 채널에 알림',
        outputKeys: ['notified'],
        settings: {},
      },
      {
        id: 'n6',
        type: 'data-storage',
        name: '감사 로그',
        icon: '💾',
        color: '#00A8CC',
        order: 6,
        connectorKey: 'metis-audit',
        actionType: 'write',
        failureAction: 'retry',
        retryCount: 3,
        description: '취약점 대응 이력 기록',
        outputKeys: ['audit_id'],
        settings: {},
      },
    ],
    connectors: ['github', 'jira', 'slack', 'metis-audit'],
    policies: [
      {
        id: 'pol-1',
        name: 'Critical 취약점 즉시 대응',
        when: 'Critical CVSS 감지 시',
        riskLevel: 'critical',
        action: 'block',
        description: 'Critical 취약점은 24시간 내 패치 필수',
      },
    ],
    monitoringRequirements: ['영향 서비스 수', '패치 진행률'],
    outputs: ['패치 우선순위 목록', '자동 생성된 티켓', '감사 기록'],
    estimatedDuration: '30-60초',
    tags: ['security', 'vulnerability', 'patch'],
  },

  // WF-8: Weekly Ops Briefing
  {
    id: 'wf-weekly-briefing',
    name: '주간 운영 KPI 브리핑',
    description:
      '매주 자동으로 운영 KPI(MTTR, 배포 실패율, 정책 위반 등)를 수집하고 경영진 보고서 생성',
    category: '모니터링',
    packId: 'pack-governance',
    targetUser: 'IT 관리자',
    businessOutcome: '수동 리포팅 제거 (주 4시간 절약)',
    triggerType: '주간 스케줄 (매주 월요일 08:00)',
    parameters: [
      {
        key: 'date_range',
        label: '기간',
        type: 'date-range',
        required: true,
        defaultValue: '지난 7일',
        description: '리포트 대상 기간',
      },
      {
        key: 'service_scope',
        label: '서비스 범위',
        type: 'select',
        required: false,
        options: ['전체', '핵심 서비스만'],
        defaultValue: '전체',
        description: '리포트 범위',
      },
    ],
    nodes: [
      {
        id: 'n1',
        type: 'schedule',
        name: '주간 스케줄',
        icon: '⏰',
        color: '#FF6B6B',
        order: 1,
        actionType: 'read',
        failureAction: 'stop',
        description: '매주 월요일 08:00 트리거',
        outputKeys: ['trigger_time'],
        settings: { scheduleType: '주간 반복', scheduleTime: '08:00', scheduleWeekday: '월요일' },
      },
      {
        id: 'n2',
        type: 'api-call',
        name: 'KPI 데이터 수집',
        icon: '🌐',
        color: '#FF6348',
        order: 2,
        connectorKey: 'prometheus',
        actionType: 'read',
        failureAction: 'stop',
        description: '인시던트, 배포, 감사, 실행 메트릭 수집',
        outputKeys: ['metrics'],
        settings: {},
      },
      {
        id: 'n3',
        type: 'api-call',
        name: 'FinOps 비용 데이터',
        icon: '🌐',
        color: '#FF6348',
        order: 3,
        actionType: 'read',
        failureAction: 'skip',
        description: '주간 AI 비용 및 최적화 현황',
        outputKeys: ['finops_stats'],
        settings: {},
      },
      {
        id: 'n4',
        type: 'ai-processing',
        name: '주간 브리핑 생성',
        icon: '🤖',
        color: '#6C5CE7',
        order: 4,
        actionType: 'execute',
        failureAction: 'fallback',
        description: 'MTTR, 재발률, 배포 실패율, Top 5 Risk, Top 5 개선안 포함 브리핑 생성',
        outputKeys: ['briefing', 'risks', 'recommendations'],
        settings: {
          agentName: 'ops-briefing-agent',
          model: 'claude-sonnet-4.6',
          finopsEnabled: true,
        },
      },
      {
        id: 'n5',
        type: 'data-storage',
        name: '리포트 저장',
        icon: '💾',
        color: '#00A8CC',
        order: 5,
        connectorKey: 'metis-evidence',
        actionType: 'write',
        failureAction: 'retry',
        retryCount: 2,
        description: '리포트 아티팩트 저장',
        outputKeys: ['report_id'],
        settings: {},
      },
      {
        id: 'n6',
        type: 'email-send',
        name: '관리자 메일 발송',
        icon: '📧',
        color: '#A29BFE',
        order: 6,
        connectorKey: 'email-smtp',
        actionType: 'external-send',
        failureAction: 'skip',
        description: '관리자 이메일로 브리핑 발송',
        outputKeys: ['email_sent'],
        settings: {},
      },
      {
        id: 'n7',
        type: 'slack-message',
        name: '운영 채널 공유',
        icon: '💬',
        color: '#00B894',
        order: 7,
        connectorKey: 'slack',
        actionType: 'external-send',
        failureAction: 'skip',
        description: '브리핑 요약을 Slack 채널에 공유',
        outputKeys: ['notified'],
        settings: {},
      },
    ],
    connectors: ['prometheus', 'email-smtp', 'slack', 'metis-evidence'],
    policies: [],
    monitoringRequirements: ['브리핑 생성 상태', '발송 완료 여부'],
    outputs: ['주간 운영 요약', 'Top 5 위험', 'Top 5 개선 권고', 'Evidence 참조'],
    estimatedDuration: '45-90초',
    tags: ['reporting', 'kpi', 'weekly'],
  },

  // WF-9: Weekly AI Governance Review
  {
    id: 'wf-ai-governance',
    name: '주간 AI Agent 거버넌스 점검',
    description:
      '매주 AI Agent 활동 로그를 분석하여 정책 위반, 비용 이상, 실패율 높은 Agent를 식별하고 조치 추천',
    category: '모니터링',
    packId: 'pack-governance',
    targetUser: 'IT 관리자 / 거버넌스 담당자',
    businessOutcome: 'Agent 운영 위험 조기 식별',
    triggerType: '주간 스케줄',
    parameters: [
      {
        key: 'date_range',
        label: '기간',
        type: 'date-range',
        required: true,
        defaultValue: '지난 7일',
        description: '점검 대상 기간',
      },
    ],
    nodes: [
      {
        id: 'n1',
        type: 'schedule',
        name: '주간 스케줄',
        icon: '⏰',
        color: '#FF6B6B',
        order: 1,
        actionType: 'read',
        failureAction: 'stop',
        description: '매주 월요일 09:00 트리거',
        outputKeys: ['trigger_time'],
        settings: { scheduleType: '주간 반복', scheduleTime: '09:00', scheduleWeekday: '월요일' },
      },
      {
        id: 'n2',
        type: 'api-call',
        name: 'AI 활동 로그 수집',
        icon: '🌐',
        color: '#FF6348',
        order: 2,
        actionType: 'read',
        failureAction: 'stop',
        description: 'FinOps 토큰 로그 및 Agent 실행 이력 수집',
        outputKeys: ['token_logs', 'execution_logs'],
        settings: {},
      },
      {
        id: 'n3',
        type: 'ai-processing',
        name: '거버넌스 분석',
        icon: '🤖',
        color: '#6C5CE7',
        order: 3,
        actionType: 'execute',
        failureAction: 'fallback',
        description: 'Top 실패 Agent, Top 비용 Agent, 정책 위반, 외부 전송 시도 등 분석',
        outputKeys: ['governance_report', 'risk_agents', 'action_recommendations'],
        settings: {
          agentName: 'governance-agent',
          model: 'claude-sonnet-4.6',
          finopsEnabled: true,
        },
      },
      {
        id: 'n4',
        type: 'data-storage',
        name: '리포트 저장',
        icon: '💾',
        color: '#00A8CC',
        order: 4,
        connectorKey: 'metis-evidence',
        actionType: 'write',
        failureAction: 'skip',
        description: '거버넌스 리포트 아티팩트 저장',
        outputKeys: ['report_id'],
        settings: {},
      },
      {
        id: 'n5',
        type: 'email-send',
        name: '관리자 발송',
        icon: '📧',
        color: '#A29BFE',
        order: 5,
        connectorKey: 'email-smtp',
        actionType: 'external-send',
        failureAction: 'skip',
        description: '거버넌스 리포트 이메일 발송',
        outputKeys: ['email_sent'],
        settings: {},
      },
      {
        id: 'n6',
        type: 'data-storage',
        name: '감사 로그',
        icon: '💾',
        color: '#00A8CC',
        order: 6,
        connectorKey: 'metis-audit',
        actionType: 'write',
        failureAction: 'skip',
        description: '거버넌스 점검 수행 기록',
        outputKeys: ['audit_id'],
        settings: {},
      },
    ],
    connectors: ['email-smtp', 'metis-evidence', 'metis-audit'],
    policies: [],
    monitoringRequirements: ['리스크 Agent 목록', 'FinOps 비용 추이'],
    outputs: ['거버넌스 리포트', '위험 순위 Agent', '조치 추천', '감사 기록'],
    estimatedDuration: '60-120초',
    tags: ['governance', 'ai-agent', 'weekly'],
  },

  // ═══════════════════════════════════════════════
  // Pack 4: Knowledge Ops Pack
  // ═══════════════════════════════════════════════

  // WF-10: CAB Decision Support
  {
    id: 'wf-cab-support',
    name: 'CAB(변경 심의) 의사결정 지원',
    description:
      '변경 요청에 대해 영향 분석, 위험 평가, 이전 유사 변경 결과를 자동 수집하여 심의 자료 생성',
    category: '자동화',
    packId: 'pack-knowledge-ops',
    targetUser: 'IT 관리자',
    businessOutcome: 'CAB 준비 시간 80% 단축, 의사결정 품질 향상',
    triggerType: '변경 요청 생성',
    parameters: [
      {
        key: 'change_id',
        label: '변경 ID',
        type: 'string',
        required: true,
        description: '변경 관리 ID',
      },
      {
        key: 'service_name',
        label: '서비스명',
        type: 'string',
        required: true,
        description: '변경 대상 서비스',
      },
    ],
    nodes: [
      {
        id: 'n1',
        type: 'webhook',
        name: '변경 요청 수신',
        icon: '🔗',
        color: '#8B4513',
        order: 1,
        connectorKey: 'jira',
        actionType: 'read',
        failureAction: 'stop',
        description: '변경 요청 생성 이벤트 수신',
        outputKeys: ['change_data'],
        settings: {},
      },
      {
        id: 'n2',
        type: 'api-call',
        name: '유사 변경 이력 조회',
        icon: '🌐',
        color: '#FF6348',
        order: 2,
        connectorKey: 'metis-knowledge',
        actionType: 'read',
        failureAction: 'skip',
        description: '과거 유사 변경의 성공/실패 이력 검색',
        outputKeys: ['similar_changes'],
        settings: {},
      },
      {
        id: 'n3',
        type: 'api-call',
        name: '서비스 의존성 분석',
        icon: '🌐',
        color: '#FF6348',
        order: 3,
        connectorKey: 'kubernetes',
        actionType: 'read',
        failureAction: 'skip',
        description: '대상 서비스의 의존성 및 영향 범위 분석',
        outputKeys: ['dependencies', 'blast_radius'],
        settings: {},
      },
      {
        id: 'n4',
        type: 'ai-processing',
        name: 'CAB 심의 자료 생성',
        icon: '🤖',
        color: '#6C5CE7',
        order: 4,
        actionType: 'execute',
        failureAction: 'fallback',
        description: '위험 점수, 영향 분석, 추천 조건, 유사 사례를 종합한 심의 자료 생성',
        outputKeys: ['cab_report', 'risk_score', 'conditions'],
        settings: {
          agentName: 'cab-support-agent',
          model: 'claude-sonnet-4.6',
          finopsEnabled: true,
        },
      },
      {
        id: 'n5',
        type: 'data-storage',
        name: '심의 자료 저장',
        icon: '💾',
        color: '#00A8CC',
        order: 5,
        connectorKey: 'metis-evidence',
        actionType: 'write',
        failureAction: 'retry',
        retryCount: 2,
        description: '심의 자료를 Evidence Pack으로 저장',
        outputKeys: ['evidence_id'],
        settings: {},
      },
      {
        id: 'n6',
        type: 'slack-message',
        name: 'CAB 채널 알림',
        icon: '💬',
        color: '#00B894',
        order: 6,
        connectorKey: 'slack',
        actionType: 'external-send',
        failureAction: 'skip',
        description: 'CAB 채널에 심의 자료 요약 공유',
        outputKeys: ['notified'],
        settings: {},
      },
    ],
    connectors: ['jira', 'metis-knowledge', 'kubernetes', 'slack', 'metis-evidence'],
    policies: [],
    monitoringRequirements: ['위험 점수', '심의 자료 생성 상태'],
    outputs: ['CAB 심의 자료', '위험 점수', '추천 조건', 'Evidence Pack'],
    estimatedDuration: '30-60초',
    tags: ['change', 'cab', 'decision-support'],
  },

  // WF-11: Incident-to-Knowledge Automation
  {
    id: 'wf-incident-knowledge',
    name: '반복 장애 패턴 자동 지식화',
    description:
      '해결된 인시던트를 분석하여 반복 패턴을 식별하고, 재사용 가능한 지식 항목(Known Error, Runbook)으로 변환',
    category: '자동화',
    packId: 'pack-knowledge-ops',
    targetUser: 'IT 운영자 / 지식 관리자',
    businessOutcome: '반복 장애 대응 시간 50% 단축',
    triggerType: '인시던트 해결 완료',
    parameters: [
      {
        key: 'incident_id',
        label: '인시던트 ID',
        type: 'string',
        required: true,
        description: '해결된 인시던트 ID',
      },
      {
        key: 'root_cause',
        label: '근본 원인',
        type: 'string',
        required: true,
        description: '식별된 근본 원인',
      },
      {
        key: 'affected_service',
        label: '영향 서비스',
        type: 'string',
        required: true,
        description: '영향받은 서비스',
      },
    ],
    nodes: [
      {
        id: 'n1',
        type: 'webhook',
        name: '인시던트 해결 이벤트',
        icon: '🔗',
        color: '#8B4513',
        order: 1,
        connectorKey: 'jira',
        actionType: 'read',
        failureAction: 'stop',
        description: '인시던트 Resolved 이벤트 수신',
        outputKeys: ['incident_data', 'resolution'],
        settings: {},
      },
      {
        id: 'n2',
        type: 'api-call',
        name: '기존 패턴 매칭',
        icon: '🌐',
        color: '#FF6348',
        order: 2,
        connectorKey: 'metis-knowledge',
        actionType: 'read',
        failureAction: 'skip',
        description: '기존 Known Error 패턴과 매칭',
        outputKeys: ['matched_patterns', 'is_new'],
        settings: {},
      },
      {
        id: 'n3',
        type: 'ai-processing',
        name: '지식 항목 생성',
        icon: '🤖',
        color: '#6C5CE7',
        order: 3,
        actionType: 'execute',
        failureAction: 'fallback',
        description: '신규/변경 패턴이면 Knowledge 항목 초안 + 대응 체크리스트 생성',
        outputKeys: ['knowledge_draft', 'checklist', 'pattern_id'],
        settings: { agentName: 'knowledge-agent', model: 'claude-sonnet-4.6', finopsEnabled: true },
      },
      {
        id: 'n4',
        type: 'wait-approval',
        name: '검토자 승인',
        icon: '⏳',
        color: '#D62828',
        order: 4,
        actionType: 'read',
        humanApproval: true,
        failureAction: 'stop',
        description: '지식 관리자가 Knowledge 항목 검토/승인',
        outputKeys: ['approval'],
        settings: { waitType: 'approval', timeoutMinutes: 4320 },
      },
      {
        id: 'n5',
        type: 'api-call',
        name: 'Knowledge Registry 저장',
        icon: '🌐',
        color: '#FF6348',
        order: 5,
        connectorKey: 'metis-knowledge',
        actionType: 'write',
        failureAction: 'retry',
        retryCount: 2,
        description: '승인된 Knowledge 항목을 Registry에 저장',
        outputKeys: ['knowledge_id'],
        settings: {},
      },
      {
        id: 'n6',
        type: 'data-storage',
        name: '감사 로그',
        icon: '💾',
        color: '#00A8CC',
        order: 6,
        connectorKey: 'metis-audit',
        actionType: 'write',
        failureAction: 'skip',
        description: '지식화 프로세스 감사 기록',
        outputKeys: ['audit_id'],
        settings: {},
      },
    ],
    connectors: ['jira', 'metis-knowledge', 'metis-audit'],
    policies: [
      {
        id: 'pol-1',
        name: '지식 게시 승인',
        when: 'Knowledge 항목 등록 전',
        riskLevel: 'medium',
        action: 'block',
        description: '검토자 승인 없이 Knowledge 등록 차단',
      },
    ],
    monitoringRequirements: ['신규 패턴 수', '승인 대기 건수'],
    outputs: ['Knowledge 항목 초안', '대응 체크리스트', '승인 결과', '감사 기록'],
    estimatedDuration: '30-60초 + 승인 시간',
    tags: ['knowledge', 'pattern', 'automation'],
  },

  // WF-12: Evidence Pack Generator
  {
    id: 'wf-evidence-pack',
    name: 'Evidence Pack 자동 생성',
    description:
      '감사/컴플라이언스 요청 시 관련 실행 이력, 로그, 승인 기록을 자동 수집하여 Evidence Pack 생성',
    category: '자동화',
    packId: 'pack-knowledge-ops',
    targetUser: 'IT 관리자 / 감사 담당자',
    businessOutcome: '감사 대응 시간 90% 단축',
    triggerType: '수동 실행 / 감사 요청',
    parameters: [
      {
        key: 'target_id',
        label: '대상 ID',
        type: 'string',
        required: true,
        description: '인시던트/변경/배포 ID',
      },
      {
        key: 'evidence_type',
        label: 'Evidence 유형',
        type: 'select',
        required: true,
        options: ['incident', 'deployment', 'change', 'agent-activity'],
        description: 'Evidence 수집 대상 유형',
      },
      {
        key: 'date_range',
        label: '기간',
        type: 'date-range',
        required: true,
        description: 'Evidence 수집 기간',
      },
    ],
    nodes: [
      {
        id: 'n1',
        type: 'webhook',
        name: 'Evidence 요청 수신',
        icon: '🔗',
        color: '#8B4513',
        order: 1,
        actionType: 'read',
        failureAction: 'stop',
        description: '감사 요청 또는 수동 실행 트리거',
        outputKeys: ['request_params'],
        settings: {},
      },
      {
        id: 'n2',
        type: 'api-call',
        name: '실행 이력 수집',
        icon: '🌐',
        color: '#FF6348',
        order: 2,
        connectorKey: 'metis-audit',
        actionType: 'read',
        failureAction: 'stop',
        description: '대상 관련 전체 실행/감사 로그 수집',
        outputKeys: ['audit_logs', 'execution_traces'],
        settings: {},
      },
      {
        id: 'n3',
        type: 'api-call',
        name: '관련 문서 수집',
        icon: '🌐',
        color: '#FF6348',
        order: 3,
        connectorKey: 'metis-knowledge',
        actionType: 'read',
        failureAction: 'skip',
        description: '관련 RCA, Knowledge, 승인 기록 수집',
        outputKeys: ['documents', 'approvals'],
        settings: {},
      },
      {
        id: 'n4',
        type: 'ai-processing',
        name: 'Evidence 요약 생성',
        icon: '🤖',
        color: '#6C5CE7',
        order: 4,
        actionType: 'execute',
        failureAction: 'fallback',
        description: '수집된 자료를 구조화하고 요약 생성',
        outputKeys: ['evidence_summary', 'artifacts_list'],
        settings: { agentName: 'evidence-agent', model: 'claude-sonnet-4.6', finopsEnabled: true },
      },
      {
        id: 'n5',
        type: 'data-storage',
        name: 'Evidence Pack 봉인',
        icon: '💾',
        color: '#00A8CC',
        order: 5,
        connectorKey: 'metis-evidence',
        actionType: 'write',
        failureAction: 'retry',
        retryCount: 3,
        description: 'Evidence Pack 생성 및 무결성 봉인',
        outputKeys: ['evidence_pack_id', 'seal_hash'],
        settings: {},
      },
      {
        id: 'n6',
        type: 'email-send',
        name: '감사자 전달',
        icon: '📧',
        color: '#A29BFE',
        order: 6,
        connectorKey: 'email-smtp',
        actionType: 'external-send',
        failureAction: 'skip',
        description: 'Evidence Pack 링크를 감사자에게 발송',
        outputKeys: ['email_sent'],
        settings: {},
      },
    ],
    connectors: ['metis-audit', 'metis-knowledge', 'metis-evidence', 'email-smtp'],
    policies: [],
    monitoringRequirements: ['수집 완료율', 'Evidence Pack 크기'],
    outputs: ['Evidence Pack', '요약 문서', '아티팩트 목록', '봉인 해시'],
    estimatedDuration: '30-90초',
    tags: ['evidence', 'audit', 'compliance'],
  },
];

// ── 4 Starter Packs ──

export const STARTER_PACKS: StarterPack[] = [
  {
    id: 'pack-incident-ops',
    name: 'Incident Ops Pack',
    description: '장애 접수부터 RCA까지 인시던트 라이프사이클 전체를 자동화하는 워크플로우 패키지',
    icon: '🚨',
    color: '#EF4444',
    category: '자동화',
    workflowIds: ['wf-incident-triage', 'wf-alert-dedup', 'wf-rca-draft'],
    requiredConnectors: [
      'jira',
      'github',
      'elk',
      'slack',
      'pagerduty',
      'metis-knowledge',
      'metis-audit',
      'metis-evidence',
    ],
    version: '1.0.0',
  },
  {
    id: 'pack-release-ops',
    name: 'Release Ops Pack',
    description: '배포 전 점검, 후 검증, DB 백업까지 릴리스 안전성을 보장하는 워크플로우 패키지',
    icon: '🚀',
    color: '#3B82F6',
    category: '배포',
    workflowIds: ['wf-pre-deploy-gate', 'wf-post-deploy-verify', 'wf-db-backup'],
    requiredConnectors: [
      'github',
      'jenkins',
      'prometheus',
      'jira',
      'slack',
      'postgresql',
      's3',
      'metis-audit',
    ],
    version: '1.0.0',
  },
  {
    id: 'pack-governance',
    name: 'Governance Pack',
    description: '보안 취약점 조율, 운영 KPI 브리핑, AI Agent 거버넌스 점검 자동화 패키지',
    icon: '🛡️',
    color: '#8B5CF6',
    category: '모니터링',
    workflowIds: ['wf-vuln-patch', 'wf-weekly-briefing', 'wf-ai-governance'],
    requiredConnectors: [
      'github',
      'jira',
      'slack',
      'prometheus',
      'email-smtp',
      'metis-evidence',
      'metis-audit',
    ],
    version: '1.0.0',
  },
  {
    id: 'pack-knowledge-ops',
    name: 'Knowledge Ops Pack',
    description: 'CAB 의사결정 지원, 반복 장애 지식화, Evidence Pack 자동 생성 패키지',
    icon: '📚',
    color: '#F59E0B',
    category: '자동화',
    workflowIds: ['wf-cab-support', 'wf-incident-knowledge', 'wf-evidence-pack'],
    requiredConnectors: [
      'jira',
      'metis-knowledge',
      'metis-audit',
      'metis-evidence',
      'kubernetes',
      'slack',
      'email-smtp',
    ],
    version: '1.0.0',
  },
];

// ── Intent Classification for Builder Planner ──

export interface IntentClassification {
  intent: string;
  keywords: string[];
  matchedTemplates: string[];
  confidence: number;
}

export const INTENT_PATTERNS: { intent: string; keywords: string[]; templateIds: string[] }[] = [
  // IT Ops 도메인
  {
    intent: 'incident-triage',
    keywords: [
      '장애',
      'incident',
      'triage',
      '접수',
      '인시던트',
      '장애접수',
      '긴급',
      '에스컬레이션',
      '장애대응',
      '장애처리',
      '오류접수',
    ],
    templateIds: ['wf-incident-triage'],
  },
  {
    intent: 'alert-management',
    keywords: [
      '알림',
      'alert',
      '중복',
      'dedup',
      '노이즈',
      '모니터링 알림',
      'pagerduty',
      '경고',
      '알람',
    ],
    templateIds: ['wf-alert-dedup'],
  },
  {
    intent: 'rca',
    keywords: [
      'rca',
      '원인분석',
      'root cause',
      '포스트모템',
      'post-mortem',
      '장애보고서',
      '원인',
      '분석보고',
    ],
    templateIds: ['wf-rca-draft'],
  },
  {
    intent: 'deployment-gate',
    keywords: [
      '배포',
      'deploy',
      '릴리스',
      'release',
      '점검',
      'gate',
      '승인',
      '배포전',
      '출시',
      '런칭',
    ],
    templateIds: ['wf-pre-deploy-gate'],
  },
  {
    intent: 'deployment-verify',
    keywords: ['배포후', '검증', 'verify', '롤백', 'rollback', 'canary', '배포확인', '배포검증'],
    templateIds: ['wf-post-deploy-verify'],
  },
  {
    intent: 'backup',
    keywords: ['백업', 'backup', 'db', '데이터베이스', '복구', 'recovery', '저장소'],
    templateIds: ['wf-db-backup'],
  },
  {
    intent: 'security',
    keywords: [
      '취약점',
      'vulnerability',
      '보안',
      'security',
      'CVE',
      '패치',
      'patch',
      '해킹',
      '위협',
    ],
    templateIds: ['wf-vuln-patch'],
  },
  {
    intent: 'reporting',
    keywords: [
      '주간',
      'weekly',
      '리포트',
      'report',
      'KPI',
      '브리핑',
      'briefing',
      '보고서',
      '보고',
      '요약',
      '일일',
      '월간',
      '정리',
      '현황',
    ],
    templateIds: ['wf-weekly-briefing'],
  },
  {
    intent: 'governance',
    keywords: [
      '거버넌스',
      'governance',
      '정책',
      'policy',
      'agent 관리',
      '비용',
      'finops',
      '규정',
      '준수',
      '관리',
    ],
    templateIds: ['wf-ai-governance'],
  },
  {
    intent: 'change-management',
    keywords: ['변경', 'change', 'CAB', '심의', '변경관리', '영향분석'],
    templateIds: ['wf-cab-support'],
  },
  {
    intent: 'knowledge',
    keywords: ['지식', 'knowledge', '패턴', 'pattern', '런북', 'runbook', 'known error', '문서화'],
    templateIds: ['wf-incident-knowledge'],
  },
  {
    intent: 'evidence',
    keywords: ['evidence', '감사', 'audit', '증거', '컴플라이언스', 'compliance', '증빙'],
    templateIds: ['wf-evidence-pack'],
  },
  // 일반 자동화 (broader patterns → 여러 템플릿 추천)
  {
    intent: 'news-briefing',
    keywords: ['뉴스', 'news', '기사', '검색', '크롤링', 'crawl', '수집', '스크래핑', '트렌드'],
    templateIds: ['wf-weekly-briefing'],
  },
  {
    intent: 'email-automation',
    keywords: ['메일', 'email', '이메일', '발송', '알림', '통보', '전송'],
    templateIds: ['wf-weekly-briefing', 'wf-incident-triage'],
  },
  {
    intent: 'ai-summary',
    keywords: [
      'ai',
      '요약',
      'summary',
      'summarize',
      '분석',
      'analyze',
      '정리',
      '인공지능',
      'gpt',
      'claude',
    ],
    templateIds: ['wf-rca-draft', 'wf-weekly-briefing'],
  },
  {
    intent: 'monitoring',
    keywords: ['모니터링', 'monitor', '감시', '헬스체크', 'health', '상태', '서버', '시스템'],
    templateIds: ['wf-alert-dedup', 'wf-post-deploy-verify'],
  },
  {
    intent: 'automation-general',
    keywords: [
      '자동화',
      'automation',
      'automate',
      '자동',
      '워크플로우',
      'workflow',
      '스케줄',
      'schedule',
      '매일',
      '매시간',
      '매주',
    ],
    templateIds: ['wf-weekly-briefing', 'wf-incident-triage'],
  },
];

/**
 * Intent Classifier: Analyze user prompt and recommend matching templates
 */
export function classifyIntent(prompt: string): IntentClassification[] {
  const lower = prompt.toLowerCase();
  const results: IntentClassification[] = [];

  for (const pattern of INTENT_PATTERNS) {
    const matchedKeywords = pattern.keywords.filter((kw) => lower.includes(kw.toLowerCase()));
    if (matchedKeywords.length > 0) {
      const confidence = Math.min(1, matchedKeywords.length / 3);
      results.push({
        intent: pattern.intent,
        keywords: matchedKeywords,
        matchedTemplates: pattern.templateIds,
        confidence,
      });
    }
  }

  return results.sort((a, b) => b.confidence - a.confidence);
}

/**
 * Get connector gap analysis for a template
 */
export function analyzeConnectorGaps(template: WorkflowTemplate): {
  available: ConnectorContract[];
  placeholder: ConnectorContract[];
  missing: string[];
} {
  const available: ConnectorContract[] = [];
  const placeholder: ConnectorContract[] = [];
  const missing: string[] = [];

  for (const key of template.connectors) {
    const connector = CONNECTOR_REGISTRY.find((c) => c.key === key);
    if (!connector) {
      missing.push(key);
    } else if (connector.status === 'available') {
      available.push(connector);
    } else {
      placeholder.push(connector);
    }
  }

  return { available, placeholder, missing };
}
