{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metis-data
  labels:
    {{- include "metis.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
